FROM golang:1.24

ENV GOFLAGS="-buildvcs=false"

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

RUN apt-get update && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*

EXPOSE 8080

CMD ["sleep", "infinity"]