FROM golang:1.24

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

RUN apt-get update && apt-get install -y nodejs npm && rm -rf /var/lib/apt/lists/*

EXPOSE 8080

RUN chown -R root:root /app

USER root

# RUN git confog --global --add safe.directory /app

CMD ["sleep", "infinity"]