services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:3.8
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - kafka-net
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.9.0
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - BITNAMI_DEBUG=yes
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - kafka-net
    depends_on:
      - zookeeper

  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    volumes:
      - .:/app
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  kafka_data:
  zookeeper_data:
