services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9094:9094'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=SECURE://:9094,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SECURE:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=SECURE://127.0.0.1:9094
      - KAFKA_NODE_ID=1
      - KAFKA_CLIENT_USERS=bob
      - KAFKA_CLIENT_PASSWORDS=bobpassword
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - BITNAMI_DEBUG=true
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SECURE
      - KAFKA_CLIENT_LISTENER_NAME=SECURE
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - kafka-net

  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - kafka
    volumes:
      - .:/app
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  kafka_data:
