services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app
    networks:
      - kafka-net
    environment:
      - KAFKA_BROKERS=localhost:9092,localhost:9095,localhost:9098  # All 3 clusters
      - KAFKA_BROKER=localhost:9092     # Primary cluster for backward compatibility
      - LOG_LEVEL=debug
    # Note: Remove depends_on since Kafka is in separate compose file
    # Use external_links or start Kafka separately

networks:
  kafka-net:
    external: true
    name: kafka-net

volumes:
  zookeeper_data:
