services:
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.dev
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app
    networks:
      - kafka-net
    environment:
      - KAFKA_BROKERS=kafka-cluster1:9093,kafka-cluster2:9093,kafka-cluster3:9093
      - KAFKA_BROKER=kafka-cluster1:9093
      - LOG_LEVEL=debug
    # Note: Remove depends_on since Kafka is in separate compose file
    # Use external_links or start Kafka separately

networks:
  kafka-net:
    external: true
    name: kafka-net

volumes:
  zookeeper_data:
