name: Tests

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - cd-setup
  workflow_dispatch:

env:
  GO_VERSION: 1.24

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Generate coverage report
        run: make test-coverage-report

        # TODO: Re-enable code coverage threshold checks
    #   - name: Check coverage threshold
    #     if: matrix.go-version == '1.24'
    #     run: |
    #       COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
    #       echo "Current coverage: ${COVERAGE}%"
    #       if (( $(echo "$COVERAGE < 80" | bc -l) )); then
    #         echo "Coverage ${COVERAGE}% is below minimum threshold of 80%"
    #         exit 1
    #       fi
    #       echo "Coverage check passed!"
